name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./ci-cd/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: v1.21.0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.8.0

    - name: Deploy to Kubernetes using Helm
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        helm upgrade --install my-app ./helm/my-app --set image.repository=${{ secrets.DOCKER_USERNAME }}/my-app --set image.tag=latest
